### ISSUE TITLE
make a v2ray like proxy tools and port to golang

### ISSUE THREAD

**Issue by ghost** [Kkevsterrr/geneva#25]
as the title tl;dr easy deploy and less traffic
make a v2ray like proxy tools which can bypass almost network package,except dns resolv package
port to golang which makes easier deploy

**Comment by Kkevsterrr** [comment]
There is a golang build of the Geneva engine, provided by the Psiphon project: https://pkg.go.dev/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/packetman hope this helps!

**Comment by 0x391F** [comment]
> There is a golang build of the Geneva engine, provided by the Psiphon project: https://pkg.go.dev/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/packetman hope this helps!

Sorry, but it said: 
`This package implements the equivilent of the Geneva "engine", which can execute packet manipulation strategies. It does not implement the genetic algorithm component.`

**Comment by lepz0r** [comment]
There's also golang port by lantern but it seemingly can only intercept on Windows

https://github.com/getlantern/geneva
https://github.com/getlantern/geneva-cli
