### ISSUE TITLE
Server side evaluation using docker

### ISSUE THREAD

**Issue by Chhavi2208** [Kkevsterrr/geneva#26]
I am trying to run the server side evaluation strategy using inbuilt censors with the help of docker.
Cmd : sudo python3 evolve.py  --server-side --test-type echo --censor censor2 --log debug

But I am receiving following error:
  File "/code/actions/utils.py", line 97, in parse
    raise actions.tree.ActionTreeParseError("Failed to parse tree")
actions.tree.ActionTreeParseError: Failed to parse tree

This error got resolved by using this modified command:
sudo python3 evolve.py --strategy "\/" --server-side --test-type echo --censor censor2 --log debug

But new error is displayed:
 File "/home/chhavi/ACN/Geneva/geneva/evaluator.py", line 256, in run_test
    ind.fitness = server.punish_fitness(ind.fitness, self.logger)
AttributeError: 'NoneType' object has no attribute 'punish_fitness'

I think the main cause of above errors are that engine is running from client side rather than server side.

Can you please tell me how to run server side evaluation using dockers.

**Comment by Kkevsterrr** [comment]
Hi @Chhavi2208 - sorry for missing this until now! The issue in your printout is `--strategy "/"` - `/` is not a valid strategy - you need either an empty string `""` or a true empty strategy `"\/"`. That should fix that issue.
