### ISSUE TITLE
listen on multi ports?

### ISSUE THREAD

**Issue by sophauer** [Kkevsterrr/geneva#27]
i run ：
engine.py --server-port 80 --strategy "[TCP:flags:PA]-duplicate(tamper{TCP:dataofs:replace:10}(tamper{TCP:chksum:corrupt},),)-|" --log debug

it worked fine,so.is it possible engine.py could listen and worked as service in multi ports,such as 1000:1200?

million TKS

**Comment by Kkevsterrr** [comment]
Hi @sophauer - we haven't added this feature, but it wouldn't be too difficult to add. I've added it to our roadmap!

**Comment by sophauer** [comment]
> Hi @sophauer - we haven't added this feature, but it wouldn't be too difficult to add. I've added it to our roadmap!

million TKS

**Comment by Kkevsterrr** [comment]
hey @sophauer - just wanted to let you know we just merged an update for this - #29 . Many thanks to @harrimd for the implementation!

**Comment by sophauer** [comment]
> hey @sophauer - just wanted to let you know we just merged an update for this - #29 . Many thanks to @harrimd for the implementation!

wow~!!
it's all we need.TKS!!
