### ISSUE TITLE
run as systemd issue

### ISSUE THREAD

**Issue by sophauer** [Kkevsterrr/geneva#31]
OS: centos 7
systemd service
`[Unit]
Description=Geneva Server
[Service]
Type=simple
User=root
WorkingDirectory=/home/centos/geneva
ExecStart=/usr/bin/python3 /home/centos/geneva/engine.py --server-port mult-ports --strategy "XXXXX"

ExecReload=/bin/kill -HUP $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target`

1st run,type iptables -L,
NFQUEUE    tcp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    udp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2

then,systemctl restart Geneva.service,
iptbables -L
NFQUEUE    tcp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    udp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    tcp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    udp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2

if i do it again,systemctl restart Geneva.service,
iptbables -L showed
NFQUEUE    tcp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    udp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    tcp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    udp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    tcp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2
NFQUEUE    udp  --  anywhere             anywhere             multiport dports XXXX NFQUEUE num 2

**Comment by Kkevsterrr** [comment]
The issue is likely how you are killing Geneva - if you kill the process without giving it time to shutdown, it will not have time to clean up those NFQUEUE rules. I would recommend changing the HUP to a SIGINT - hopefully that should resolve the issue!

**Comment by sophauer** [comment]
TKS,rsolved!
