### ISSUE TITLE
Running geneva on server side (router)

### ISSUE THREAD

**Issue by Hi-Timofey** [Kkevsterrr/geneva#33]
Hello, there are quote in your README that  you can run the Geneva from the server side, but i found no docs for this case.
Is there anyway to launch this on router (for example Openwrt) for avoiding DPI. How it will work as a server. May be there are some links I haven't seen.

**Comment by Kkevsterrr** [comment]
@Hi-Timofey you should be able to just add the `--server-side` flag - there are (some) docs here: https://geneva.readthedocs.io/en/latest/howitworks/evaluator.html?highlight=server-side#server-side-evaluation, but I should update the rest to make it more clear. Hope this helps!

**Comment by Hi-Timofey** [comment]
> @Hi-Timofey you should be able to just add the `--server-side` flag - there are (some) docs here: https://geneva.readthedocs.io/en/latest/howitworks/evaluator.html?highlight=server-side#server-side-evaluation, but I should update the rest to make it more clear. Hope this helps!

I read some docs and have quesion. Is there any way to route all traffic to geneva with `--server-side` ? For example I have 2 PC's and want to make geneva to evade all traffic from my ISP.

**Comment by Kkevsterrr** [comment]
Hi @Hi-Timofey - 

> I read some docs and have quesion. Is there any way to route all traffic to geneva with --server-side ? For example I have 2 PC's and want to make geneva to evade all traffic from my ISP.

The goal of the --server-side flag is to setup Geneva to run at the server-side of the connection - are you trying to use it as a server, or as a client? As far as how to route traffic to Geneva, by default it captures traffic on a given port. You could run it on a raspberry pi or something similar (kind of like a PiHole https://pi-hole.net/), but you'd have to set up that up - we haven't experimented with that ourselves yet. 

Hope this helps!
