### ISSUE TITLE
Engine: Ability to set log file logging level

### ISSUE THREAD

**Issue by lepz0r** [Kkevsterrr/geneva#37]
Currently Geneva `engine.py` always write log to file with logging level debug regardless of `--log` level parameter, but it can be problem when downloading a large file or having too many connections, the log file can grow so quickly

**Comment by Kkevsterrr** [comment]
Can you share how are you invoking the engine? If running `engine.py` directly, `--log` _should_ control the logger; if that's not working, I'll mark this a bug

**Comment by lepz0r** [comment]
the logger that output to terminal can be controlled with `--log` but logger that output to to `trials/log/<environtment-id>.engine.log` can't be controlled with `--log`, I run geneva with `sudo python3 engine.py --server-port 80,443 --environment-id cincin28 --strategy "[TCP:flags:PA]-fragment{tcp:8:True}(,fragment{tcp:4:True})-|" --log info --no-save-packets` which output nothing to the terminal but output something like this file to `trials/log/cincin28.engine.log` 
[cincin28.engine_info.log](https://github.com/Kkevsterrr/geneva/files/9660518/cincin28.engine_info.log)
