### ISSUE TITLE
Iran Needs You

### ISSUE THREAD

**Issue by zebka** [Kkevsterrr/geneva#38]
Hi There,
Iranian people are under a heavy filtering service by gov. I myself accidentally and by chance connected to web and come here to say that, we needs you guys and your help.
if you can help and get some fast tip answer this issue pls.

Best Regards - Iranian People

**Comment by Kkevsterrr** [comment]
I recommend Psiphon: https://psiphon.ca/ they have integrated many of our strategies and findings, and they are still operational in Iran. Best of luck!
