### ISSUE TITLE
Failure when the number of connections are huge!

### ISSUE THREAD

**Issue by shayan775** [Kkevsterrr/geneva#67]
i run it in server mode and with no strategy with the command `python3 engine.py --server-port 2083 --strategy "\/" --server-side --log debug` for debugging, it works fine when the number of connections are low, but when it reaches about 15k of connections, the client side will fail!

**Comment by Kaimar666** [comment]
这是一封自动回复邮件。已经收到您的来信。

**Comment by Kkevsterrr** [comment]
Hi @shayan775 - thanks for testing! This repo of Geneva was never designed for high throughput - it's a research prototype to prove out the idea. You may be interested in Lantern or Psiphon's rewrites of Geneva's engine: 

Lantern: https://github.com/getlantern/geneva
Psiphon: https://pkg.go.dev/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/packetman

Both are written in Golang, and designed much more for performance. I hope this helps!
